#ifndef SETPOINT_MSG_ATTITUDE_DEFINES
#define SETPOINT_MSG_ATTITUDE_DEFINES

#define IGNORE_ROLL_RATE (1 << 0)
#define IGNORE_PITCH_RATE (1 << 1)
#define IGNORE_YAW_RATE (1 << 2)
#define IGNORE_THRUST (1<< 6)
#define IGNORE_ATTITUDE (1 << 7)

#endif
